apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vs-lab
  name: backendspringboot
  labels:
    service: 
      backendspringboot
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backendspringboot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: backend
        app: vs-lab
        service: 
          backendspringboot
    spec:
      restartPolicy: Always
      containers:
        - name: backendspringboot
          image: maeddes/backendspringboot:hse24
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
