apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vs-lab
  name: vs-backend
  labels:
    service: 
      vs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vs-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: backend
        app: vs-lab
        service: 
          vs-backend
    spec:
      restartPolicy: Always
      containers:
        - name: vs-backend
          image: maeddes/backendspringboot:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
