apiVersion: v1
kind: Deployment
metadata:
  namespace: vs-lab
  name: vs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vs-frontend
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: vs-frontend
          image: e2neo/vs-lab/frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            containerPort: 8080
            hostPort: 8080
            protocol: TCP
