apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vs-lab
  name: vs-frontend
  labels:
    service: 
      vs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vs-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: frontend
        app: vs-lab
        service: 
          vs-frontend
    spec:
      restartPolicy: Always
      containers:
        - name: vs-frontend
          image: verteilte-systeme-lab_frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
