apiVersion: v1
kind: Service
metadata:
  namespace: vs-lab
  name: shoppingdb
  labels:
    service: shoppingdb
spec:
  type: LoadBalancer
  ports:
    - name: "db"
      port: 5432
      targetPort: 5432
  selector:
    service: shoppingdb
    app: vs-lab
    tier: database