apiVersion: v1
kind: Service
metadata:
  namespace: vs-lab
  name: backendspringboot
  labels:
    service: backendspringboot
spec:
  ports:
    - name: "app"
      port: 8080
      targetPort: 8080
  selector:
    service: backendspringboot
    app: vs-lab
    tier: backend