apiVersion: v1
kind: Service
metadata:
  namespace: vs-lab
  name: vs-backend
  labels:
    service: vs-backend
spec:
  ports:
    - name: "app"
      port: 8080
      targetPort: 8080
  selector:
    service: vs-backend
    app: vs-lab
    tier: backend